### ISSUE TITLE
Add Additional Instructions Regarding GSSAPI Error On WSL/Linux

### ISSUE THREAD

**Issue by AjkayAlan** [microsoft/artifacts-keyring#7]
While trying to use this in WSL 1 (Ubuntu 18.04 LTS), I was running into the following issue when attempting to install a package from my artifact feed after installing artifacts-keyring:

```sh
Unhandled Exception: System.ComponentModel.Win32Exception: GSSAPI operation failed with error - An invalid status code was supplied (Unknown error). 
   at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
   at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken can
cellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, Cancellation
Token cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NuGetCredentialProvider.CredentialProviders.Vsts.AuthUtil.GetResponseHeadersAsync(Uri uri, CancellationToken cancellationToken)
   at NuGetCredentialProvider.CredentialProviders.Vsts.AuthUtil.IsVstsUriAsync(Uri uri)
   at NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider.CanProvideCredentialsAsync(Uri uri)
   at NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.HandleRequestAsync(GetAuthenticationCredentialsRequest request)
   at NuGetCredentialProvider.Program.Main(String[] args)
   at NuGetCredentialProvider.Program.<Main>(String[] args)
WARNING: Keyring is skipped due to an exception: Failed to get credentials: process with PID 17938 exited with code -6; additional error message: 
```

Doing some searching I found https://stackoverflow.com/questions/50276060/a-call-to-sspi-failed-gssapi-operation-failed-with-error-an-invalid-status-cod for an unrelated issue with running WCF based .NET core code on Linux, but had a similar error as mine, which ended up fixing my problem.

For WSL/Linux users running into as GSSAPI error, they may need to run the following (example given for debian):
```sh
sudo apt-get update && sudo apt-get install -y --no-install-recommends gss-ntlmssp
```

Should this information be added to the docs or readme?

**Comment by zooba** [comment]
It looks like .NET Core 3.0 has the fix (https://github.com/dotnet/corefx/issues/34879), so updating to use that is probably the better long term solution.

That workaround seems like an okay thing to advertise though. (I'm not a maintainer of this repo though, so that's just a vote, not an offer to merge it.)

**Comment by AjkayAlan** [comment]
> better long term solution

Good catch, indeed if updating this library to .NET Core 3.0 corrects the issue, that would be the better solution.
